#!/usr/bin/env python3
#this library allows us to generate UUID values.
import uuid

# anything generated by input is automatically a string
howmany = int(input("How many UUIDs should be generated? ")) # user input becomes integer not string

print("Generating UUIDs...")

# range is required because an int cannot be looped
for rando in range(howmany):
    print( uuid.uuid4() )

